#!/bin/bash

echo "🔐 Setting up Firebase Secret on Hugging Face Space"
echo "===================================================="
echo ""
echo "To store Firebase credentials securely:"
echo ""
echo "1. Go to: https://huggingface.co/spaces/yeduru/abhi/settings"
echo ""
echo "2. Scroll to 'Repository secrets'"
echo ""
echo "3. Click 'New secret'"
echo ""
echo "4. Name: FIREBASE_CREDENTIALS"
echo ""
echo "5. Value: Copy the content below (entire JSON):"
echo ""
echo "---START COPY FROM HERE---"
cat hf_space_deploy/firebase-credentials.json
echo ""
echo "---END COPY HERE---"
echo ""
echo "6. Click 'Add secret'"
echo ""
echo "7. Your Space will automatically rebuild"
echo ""
echo "✅ Done! Firebase will be enabled after rebuild."
